---
 run: 5 # id for the training
 seed: 666 # random seed for the random module

 # directory configuration
 cluster_file_dir: "../data/clusters_after_remove_files_with_no_popsa.yaml"
 pocket_dir: "../data/googlenet-dataset/"
 pop_dir: "../data/pops-googlenet/"
 trained_model_dir: "../trained_models/"
 loss_dir: "./results/"

 # dataset configuration
 merge_info: [[0, 9, 12, 25], [1, 5, 11, 22], 2, [3, 8, 13], 4, 6, [7, 19, 21], [10, 16], 15, 17, 18, 20, 23, 24, 26, [27, 30], 28, 29]
 features_to_use: ['r', 'theta', 'phi', 'sasa', 'charge', 'hydrophobicity', 'binding_probability', 'sequence_entropy']   

 # model configuration 
 which_model: 'jk' # 'jk', 'residual' or 'normal'
 model_size: 80 # size of the neural network

 # FocalLoss configuration
 which_loss: 'Focal' # 'CrossEntropy' or 'Focal'
 initial_focal_gamma: 0
 focal_gamma_ascent: True
 focal_gamma_ascent_epoch: [30, 70] # gamma = 1, 2

 # train configuration
 num_epoch: 100
 lr_decay_epoch: 50
 batch_size: 256
 learning_rate: 0.003
 weight_decay: 0.0005




